script: rake spec:all
before_script:
  - psql -c 'create database fast_seeder_test;' -U postgres
  - mysql -e 'create database fast_seeder_test;'
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby
  - ree
  - rbx-18mode
  - rbx-19mode
branches:
  only:
    - master
