language: ruby
script: rake spec
before_script:
  - psql -c 'create database fast_seeder_test;' -U postgres
  - mysql -e 'create database fast_seeder_test;'
rvm:
  - 1.8.7
  - 1.9.3
  - ree
env:
   - ADAPTER=postgresql
   - ADAPTER=mysql
   - ADAPTER=mysql2
   - ADAPTER=sqlite3
branches:
  only:
    - master
