<% if ENV['ADAPTER'] == 'mysql' %>
development:
  adapter: mysql
  database: fast_seeder_development
  username: root
  encoding: utf8

test:
  adapter: mysql
  database: fast_seeder_test
  username: root
  encoding: utf8


<% elsif ENV['ADAPTER'] == 'mysql2' %>
development:
  adapter: mysql2
  database: fast_seeder_development
  username: root
  encoding: utf8

test:
  adapter: mysql2
  database: fast_seeder_test
  username: root
  encoding: utf8


<% elsif ENV['ADAPTER'] == 'sqlite3' %>
development:
  adapter: sqlite3
  database: "db/development.sqlite3"
  timeout: 500
test:
  adapter: sqlite3
  database: "db/test.sqlite3"
  timeout: 500


<% elsif ENV['ADAPTER'] == 'postgresql' %>
development:
  adapter: postgresql
  encoding: unicode
  database: fast_seeder_development
  pool: 5
  username: postgres
  password: secret
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: fast_seeder_test
  pool: 5
  username: postgres
  password: secret
  host: localhost

<% else %>
  <% raise "ADAPTER environment variable should be specified with one of: mysql, mysql2, sqlite3, postgresql" %>
<% end %>
